name: basada
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: 4.6.5
  flutter_screenutil: 5.5.4
  get_storage: 2.0.3
  intl: 0.17.0
  google_maps_flutter: 2.2.1
  cached_network_image: 3.2.2
  firebase_messaging: 12.0.1
  firebase_core: ^1.19.1
  geocoding: ^2.0.1
  location: ^4.3.0
  image_picker: 0.8.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

