name: basada
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.7.4
  firebase_core: ^2.22.0
  flutter_native_splash: ^2.2.14
  flutter_launcher_icons: ^0.13.1
  geocoding: ^2.0.1
  location: ^5.0.3
  image_picker: ^1.0.4
  url_launcher: ^6.1.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/basada.png"
  min_sdk_android: 21 
